name: BLOOM CentOS

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  centos-9-job:
    runs-on: ubuntu-latest  # We use the default GitHub runner to start a Docker container

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run CentOS 9 container
        run: |
          docker run --name centos9-container -d centos:9 sleep infinity
          docker exec -it centos9-container yum install -y python3 python3-pip
          docker exec -it centos9-container python3 -m pip install --upgrade pip
          docker cp . centos9-container:/workspace
          docker exec -it centos9-container /bin/bash -c "cd /workspace && pip3 install pytest psycopg2-binary sqlalchemy zebra_day==0.3.0.4 pytz fedex_tracking_day==0.2.6 && source bloom_lims/env/install_postgres.sh skip && pytest"
          
      - name: Clean up Docker container
        run: docker rm -f centos9-container
