name: BLOOM LIMS Build Tests, MacOS, Ubuntu & CentOS

on: [push]

jobs:
  macos-job:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.12.0  # Update to your required Python version
          activate-environment: BLOOM
          environment-file: bloom_env.yaml  # If you have an environment file
          auto-activate-base: false

      - name: Run custom PostgreSQL setup script (if applicable)
        run: |
         pip3 install pytest psycopg2-binary sqlalchemy  zebra_day==0.3.0.4 pytz fedex_tracking_day==0.2.6
         source bloom_lims/env/install_postgres.sh ghmac
         pytest

  ubuntu-22-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.12.0  # Update to your required Python version
          activate-environment: BLOOM
          environment-file: bloom_env.yaml  # If you have an environment file
          auto-activate-base: false

      - name: Run custom PostgreSQL setup script (if applicable)
        shell: bash -l {0}
        run: |
          pip3 install pytest psycopg2-binary sqlalchemy  zebra_day==0.3.0.4 pytz fedex_tracking_day==0.2.6
          source bloom_lims/env/install_postgres.sh skip
          pytest

  centos-stream-job:
    runs-on: ubuntu-latest  # Host OS for the Docker container

    container:
      image: quay.io/centos/centos:stream9  # Using CentOS Stream 9

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          dnf install -y python3
          python3 -m ensurepip
          python3 -m pip install --upgrade pip

      - name: Set up Miniconda
        run: |
          dnf install -y wget sudo
          useradd -m bloom
          echo 'bloom ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
          
          # Create the setup script
          cat <<'EOF' >setup_bloom.sh
          #!/bin/bash
          cd /home/bloom
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p /home/bloom/miniconda
          export PATH="/home/bloom/miniconda/bin:$PATH"
          conda init
          pwd
          sleep 5
          source /home/bloom/.bashrc          
          conda env list
          sleep 5
          source bloom_lims/env/install_postgres.sh
          pytest
          EOF

          # Make the script executable
          chmod +x setup_bloom.sh

          # Execute the script as the 'bloom' user
          sudo -u bloom ./setup_bloom.sh